/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as SearchRouteImport } from './routes/search'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as ApiEventsTicketmasterRouteImport } from './routes/api.events.ticketmaster'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsTicketmasterRoute = ApiEventsTicketmasterRouteImport.update({
  id: '/api/events/ticketmaster',
  path: '/api/events/ticketmaster',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/api/events/ticketmaster': typeof ApiEventsTicketmasterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/api/events/ticketmaster': typeof ApiEventsTicketmasterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/api/events/ticketmaster': typeof ApiEventsTicketmasterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/search'
    | '/watchlist'
    | '/event/$eventId'
    | '/api/events/ticketmaster'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/search'
    | '/watchlist'
    | '/event/$eventId'
    | '/api/events/ticketmaster'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/search'
    | '/watchlist'
    | '/event/$eventId'
    | '/api/events/ticketmaster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  SearchRoute: typeof SearchRoute
  WatchlistRoute: typeof WatchlistRoute
  EventEventIdRoute: typeof EventEventIdRoute
  ApiEventsTicketmasterRoute: typeof ApiEventsTicketmasterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/ticketmaster': {
      id: '/api/events/ticketmaster'
      path: '/api/events/ticketmaster'
      fullPath: '/api/events/ticketmaster'
      preLoaderRoute: typeof ApiEventsTicketmasterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  SearchRoute: SearchRoute,
  WatchlistRoute: WatchlistRoute,
  EventEventIdRoute: EventEventIdRoute,
  ApiEventsTicketmasterRoute: ApiEventsTicketmasterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
